site_name: Danube Pub-Sub messaging documentation
nav:
        - Home: index.md
        - Getting Started:
                  - Run Danube on VMs or Bare Metal: getting_started/Danube_on_vms.md
                  - Run Danube on Kubernetes Cluster: getting_started/Danube_on_k8s_helm.md
        - Architecture:
                  - Danube architecture: architecture/architecture.md
                  - Danube service components: architecture/internal_danube_services.md
                  - Pub-Sub messaging: architecture/Queuing_PubSub_messaging.md
                  - PubSub vs Streaming: architecture/PubSub_messaging_vs_Streaming.md
        - Client Libraries:
                  - Rust client:
                            - Setup: client_libraries/Rust_client/setup.md
                            - Usage: client_libraries/Rust_client/usage.md
                  - Go client:
                            - Setup: client_libraries/Go_client/setup.md
        - Admin API:
                  - Danube CLI:
                            - Brokers: admin_API/danube_admin/brokers.md
                            - Namespaces: admin_API/danube_admin/namespaces.md
                            - Topics: admin_API/danube_admin/topics.md
        - Development:
                  - Development Environment: development/dev_environment.md
                  - Metadata Resources: development/internal_resources.md
theme:
        name: material
markdown_extensions:
        - pymdownx.highlight:
                  anchor_linenums: true
                  line_spans: __span
                  pygments_lang_class: true
        - pymdownx.inlinehilite
        - pymdownx.snippets
        - pymdownx.superfences
